### ISSUE TITLE
timestamps are off with a factor 1000

### ISSUE THREAD

**Issue by nielslaukens** [cosmonawt/ultracdn-exporter#2]
Hi,

We're trying to use this exporter to pull our CDN-metrics in to Prometheus. However, it doesn't work.

After some troubleshooting, it seems that some provided timestamps are off by a factor 1000, causing Prometheus to ignore whole scrape

```
[...]
leaseweb_ultracdn_bandwidth_per_second_bytes{distribution_group="xxx",distribution_group_id="di-xxxxxxxx"} 4804.266666666666 1576158900000000
leaseweb_ultracdn_bandwidth_per_second_bytes{distribution_group="yyy",distribution_group_id="di-yyyyyyyy"} 0 1576142626000
[...]
```

It seams that all locally generated timestamps (from cache) are correct, but the ones exposed from Leaseweb are off.

**Comment by cosmonawt** [comment]
Hello, sorry for the long delay, I somehow missed the notification on this.
The PR to fix this is now merged, and the issue should be fixed. If it is not, please re-open.
